theme: jekyll-theme-minimal
# Site Settings
locale                   : "ko-KR"
title                    : "MathPy"
title_separator          : "-"
name                     : "OtakoidTony"
description              : "OtakoidTony's Website"
logo                     : "https://raw.githubusercontent.com/OtakoidTony/homepage/master/42537ffcdee282d307071933704c5d61.jpg"
