theme: jekyll-theme-minimal
# Site Settings
locale                   : "ko-KR"
title                    : "MathPy"
title_separator          : "-"
name                     : "OtakoidTony"
description              : "OtakoidTony's Website"
logo                     : "https://raw.githubusercontent.com/OtakoidTony/homepage/master/34558575_242681683154508_4770301359691923456_n.jpg"
