theme: jekyll-theme-minimal
locale                   : "ko-KR"
title                    : "OtakoidTony's Website"
title_separator          : "-"
name                     : "OtakoidTony"
description              : ""
logo                     : "https://raw.githubusercontent.com/OtakoidTony/homepage/master/34558575_242681683154508_4770301359691923456_n.jpg"
