theme: jekyll-theme-minimal
# Site Settings
locale                   : "ko-KR"
title                    : "MathPy"
title_separator          : "-"
name                     : "OtakoidTony"
description              : "OtakoidTony's Website"
